feat(components): add documentation to all exported types
equinor/mad pull request #162
Opened 2023-08-13 07:14 UTC by HaakonSvane

- Write docstrings for all exported types

closes #103

2023-08-13 08:09 UTC, HaakonSvane commented
Don't be alarmed by all the files changed 🥇

2023-08-15 07:06 UTC, tormodAase requested changes
Good shit! The typos are probably nice to get rid of, and I have some improvement proposals regarding typography bold/italic props.

2023-08-15 07:24 UTC, tormodAase commented on packages/components/src/components/Spacer/types.ts
> +};
Maybe add a `@see https://eds.equinor.com/0b0c666ab/p/721e1f-spacing/b/0899da`.
Also wouldn't hurt to tell the user what it defaults to

2023-08-16 07:04 UTC, HaakonSvane commented on packages/components/src/components/Button/ButtonGroup.tsx
> +     */
fixed in b7711ae

2023-08-16 07:05 UTC, HaakonSvane commented on packages/components/src/components/Cell/index.ts
> +     * A container for grouping cells togehter. The child cells visually come together inside a group.
fixed in f62e1ec

2023-08-16 07:05 UTC, HaakonSvane commented on packages/components/src/components/Input/Input.tsx
> +     * Secondary small label text to add tot he input field.
fixed in 7c646f1

2023-08-16 07:06 UTC, HaakonSvane commented on packages/components/src/components/Portal/PortalContext.tsx
> +     * Deletes the portal from the registery.
fixed in d76721b

2023-08-16 08:29 UTC, HaakonSvane commented on packages/components/src/components/Spacer/types.ts
> +};
fixed in 25cd7d5

2023-08-16 08:34 UTC, tormodAase approved these changes

2023-08-16 08:34 UTC, merged