fix(button): remove `View` to fix `style` prop
equinor/mad pull request #276
Opened 2023-11-21 14:42 UTC by dansvend

- Remove wrapper `View` to make the `style` prop on `Button` behave as expected.
- Rename `ButtonProps` to `ButtonSpecificProps`.
- Update `ButtonProps` include `ViewProps`.

Closes #170

2023-11-25 09:09 UTC, HaakonSvane requested changes
Good stuff. Nice to see this cleaned out. Buttons seem to behave the same as before which is nice. Is this a breaking change? Nonetheless, I think we should add a changeset explaining that we now export the full button props.

2023-11-27 11:42 UTC, dansvend commented
> Good stuff. Nice to see this cleaned out. Buttons seem to behave the same as before which is nice. Is this a breaking change? Nonetheless, I think we should add a changeset explaining that we now export the full button props.

I believe it's not a breaking change, but I worked around this bug by wrapping a `Button` in a `View`, so there's probably some project code which can be removed after this fix.

I agree - I'll add a changeset 💪

2023-11-29 12:39 UTC, tormodAase approved these changes

2023-11-29 12:43 UTC, HaakonSvane approved these changes
Really nice. Helpful changeset 📖

2023-11-29 12:44 UTC, merged