Feat/add inputs
equinor/mad pull request #77
Opened 2023-04-27 09:41 UTC by hathibelagal-dev2

2023-04-27 12:23 UTC, HaakonSvane requested changes
Great job! This looks very good. Code pretty much is in tune with the rest of the library as well. Awesome. 
For the technical stuff, I have left some comments for you to read.
When it comes to the design, I just had a talk with @EmilieOlsen regarding some visual changes.

- The label above the text inputs should be smaller in size (0.75*base), regular font and tertiary coloring.
- The left padding of the label text should be in alignment with EDS and should not be affected by the adornments as they are now
- The adornments should have the same background color as the text input so that they look more integrated with the text field

2023-04-27 12:23 UTC, HaakonSvane commented on packages/components/src/components/TextField/TextField.tsx
After playing around with it a little bit, I noticed that the selectable area of the text field is a little small in comparison with the rest of the component. What I mean is that there are areas of the gray container that will not respond to touch. Maybe look into expanding the text area of this area, if that makes sense

2023-04-27 13:02 UTC, hathibelagal-dev2 commented on packages/components/src/styling/masterToken.ts
> +                light: "#FFFFFF",
This should probably be moved to a new issue. I find it hard to map https://www.figma.com/file/0TbIXrrObWj80Cf7KucKYFL0/Design-Tokens?type=design&node-id=2-3&t=TXomYnfWoY2Yq11I-0 to masterToken.

2023-04-28 10:20 UTC, hathibelagal-dev2 commented
I think by having that extra padding, we're forcing users to not give a background to the left and right adornments. Here's eds-core-react's Input with a background 
![image](https://user-images.githubusercontent.com/127299081/235122145-a8aad8c4-abb8-4151-a137-5890716a49a2.png)

2023-04-28 11:32 UTC, HaakonSvane requested changes

2023-04-28 11:32 UTC, HaakonSvane commented on packages/components/src/components/TextField/TextField.tsx
> +            fontFamily: theme.typography.basic.p.fontFamily,
You can do

```ts
textInput: {
    color: theme.colors.text.primary,
    ...theme.typography.basic.p
}
```

to destructure everything in the font token. Makes the style a little bit more dynamic

2023-04-28 11:32 UTC, HaakonSvane commented on packages/components/src/components/TextField/TextField.tsx
> +            fontFamily: theme.typography.basic.p.fontFamily,
Same as the other comment regarding destructuring

2023-04-28 11:32 UTC, HaakonSvane commented on packages/components/src/styling/masterToken.ts
>                  fontFamily: "Equinor-Bold",
This should be regular and not bold

2023-04-28 13:12 UTC, merged